import { useState, type FormEvent, type ChangeEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Save, Loader2 } from 'lucide-react';
import { DashboardLayout } from '@/components/layouts';
import { Card, Button, Input, Textarea } from '@/components/ui';
import { FileUpload } from '@/components/ui/FileUpload';
import { DynamicList } from '@/components/ui/DynamicList';
import { useLanguage } from '@/context/LanguageContext';
import { 
  useCreateCourseMutation, 
  useGetCategoriesQuery,
  type CreateCoursePayload 
} from '@/store/features/instructor/instructorApiSlice';
import ReactQuill from 'react-quill-new';
import 'react-quill-new/dist/quill.snow.css';
import { toast } from 'react-hot-toast';

type Step = 1 | 2 | 3;

export function InstructorCreateCoursePage() {
  const { language } = useLanguage();
  const navigate = useNavigate();
  const [createCourse, { isLoading: isSubmitting }] = useCreateCourseMutation();
  const { data: categories = [], isLoading: isLoadingCategories } = useGetCategoriesQuery();

  const [formData, setFormData] = useState<CreateCoursePayload>({
    title: '',
    slug: '',
    thumbnail: '',
    subtitle: '',
    description: '',
    category_id: 0,
    type: 'self_paced',
    level: 'beginner',
    language: 'Indonesia',
    price: 0,
    discount_price: 0,
    requirements: [],
    outcomes: [],
    target_audience: [],
  });

  const [currentStep, setCurrentStep] = useState<Step>(1);
  const [slugAutogenerated, setSlugAutogenerated] = useState(true);
  const [thumbnailFile, setThumbnailFile] = useState<File | null>(null);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const handleInputChange = (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    
    setFormData((prev: CreateCoursePayload) => {
      const newData = { ...prev, [name]: value };
      
      // Auto-generate slug from title if enabled
      if (name === 'title' && slugAutogenerated) {
        newData.slug = value
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/(^-|-$)+/g, '');
      }
      
      return newData;
    });
  };

  const handleNumberChange = (e: ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev: CreateCoursePayload) => ({ ...prev, [name]: Number(value) }));
  };

  const handleFileChange = (file: File | null) => {
    if (file) {
      setThumbnailFile(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        setFormData((prev: CreateCoursePayload) => ({ ...prev, thumbnail: reader.result as string }));
      };
      reader.readAsDataURL(file);
    } else {
      setThumbnailFile(null);
      setFormData((prev: CreateCoursePayload) => ({ ...prev, thumbnail: '' }));
    }
  };

  const validateStep = (step: Step) => {
    const newErrors: Record<string, string> = {};
    if (step === 1) {
      if (!formData.title) newErrors.title = language === 'id' ? 'Judul kursus wajib diisi' : 'Course title is required';
      if (!formData.slug) newErrors.slug = language === 'id' ? 'Slug wajib diisi' : 'Slug is required';
      if (!formData.description || formData.description === '<p><br></p>') {
        newErrors.description = language === 'id' ? 'Deskripsi wajib diisi' : 'Description is required';
      }
      if (formData.category_id === 0) newErrors.category_id = language === 'id' ? 'Kategori wajib dipilih' : 'Category is required';
    } else if (step === 2) {
      if (formData.price === undefined || formData.price < 0) {
        newErrors.price = language === 'id' ? 'Harga tidak valid' : 'Price is invalid';
      }
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const nextStep = () => {
    if (validateStep(currentStep)) {
      setCurrentStep((prev) => (prev + 1) as Step);
    }
  };

  const prevStep = () => {
    setCurrentStep((prev) => (prev - 1) as Step);
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!validateStep(3)) return;

    try {
      const formDataToSend = new FormData();
      formDataToSend.append('title', formData.title);
      formDataToSend.append('slug', formData.slug);
      formDataToSend.append('subtitle', formData.subtitle);
      formDataToSend.append('description', formData.description);
      formDataToSend.append('category_id', String(formData.category_id));
      formDataToSend.append('type', formData.type);
      formDataToSend.append('level', formData.level);
      formDataToSend.append('language', formData.language);
      formDataToSend.append('price', String(formData.price));
      
      if (formData.discount_price && formData.discount_price > 0) {
        formDataToSend.append('discount_price', String(formData.discount_price));
      }

      if (thumbnailFile) {
        formDataToSend.append('thumbnail', thumbnailFile);
      }

      formData.requirements.forEach((req, index) => formDataToSend.append(`requirements[${index}]`, req));
      formData.outcomes.forEach((out, index) => formDataToSend.append(`outcomes[${index}]`, out));
      formData.target_audience.forEach((aud, index) => formDataToSend.append(`target_audience[${index}]`, aud));

      await createCourse(formDataToSend).unwrap();
      toast.success(language === 'id' ? 'Kursus berhasil dibuat!' : 'Course created successfully!');
      navigate('/instructor/courses');
    } catch (error) {
      toast.error(language === 'id' ? 'Gagal membuat kursus' : 'Failed to create course');
    }
  };

  return (
    <DashboardLayout>
      <div className="max-w-4xl mx-auto pb-10">
        <div className="flex items-center gap-4 mb-6">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate('/instructor/courses')}
            className="rounded-full aspect-square p-2"
          >
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">
              {language === 'id' ? 'Buat Kursus Baru' : 'Create New Course'}
            </h1>
            <p className="text-gray-600">
              {language === 'id' 
                ? 'Isi informasi kursus Anda di bawah ini.' 
                : 'Fill in your course information below.'}
            </p>
          </div>
        </div>

        {/* Step Indicator */}
        <div className="flex items-center justify-between mb-8 relative">
          <div className="absolute top-1/2 left-0 w-full h-0.5 bg-gray-200 -translate-y-1/2 -z-10" />
          {[1, 2, 3].map((step) => (
            <div key={step} className="flex flex-col items-center">
              <div
                className={`w-10 h-10 rounded-full flex items-center justify-center text-sm font-bold border-2 transition-all ${
                  currentStep >= step
                    ? 'bg-blue-600 border-blue-600 text-white'
                    : 'bg-white border-gray-300 text-gray-500'
                }`}
              >
                {step}
              </div>
              <span className={`text-xs mt-2 font-medium ${currentStep >= step ? 'text-blue-600' : 'text-gray-500'}`}>
                {step === 1 
                  ? (language === 'id' ? 'Informasi Dasar' : 'Basic Info')
                  : step === 2
                  ? (language === 'id' ? 'Harga & Media' : 'Pricing & Media')
                  : (language === 'id' ? 'Kurikulum' : 'Curriculum')}
              </span>
            </div>
          ))}
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Step 1: Basic Information */}
          {currentStep === 1 && (
            <Card className="p-6 space-y-4">
              <h2 className="text-lg font-semibold text-gray-900 border-b pb-2 mb-4">
                {language === 'id' ? 'Informasi Dasar' : 'Basic Information'}
              </h2>
              
              <div className="grid md:grid-cols-2 gap-4">
                <Input
                  label={language === 'id' ? 'Judul Kursus' : 'Course Title'}
                  name="title"
                  value={formData.title}
                  onChange={handleInputChange}
                  disabled={isSubmitting}
                  error={errors.title}
                  required
                />
                <Input
                  label="Slug"
                  name="slug"
                  value={formData.slug}
                  onChange={(e) => {
                    setSlugAutogenerated(false);
                    handleInputChange(e);
                  }}
                  disabled={isSubmitting}
                  error={errors.slug}
                  required
                />
              </div>

              <Input
                label={language === 'id' ? 'Subjudul' : 'Subtitle'}
                name="subtitle"
                value={formData.subtitle}
                onChange={handleInputChange}
                disabled={isSubmitting}
              />

              <div className="space-y-1">
                <label className="block text-sm font-medium text-gray-700">
                  {language === 'id' ? 'Deskripsi' : 'Description'} <span className="text-red-500">*</span>
                </label>
                <div className="bg-white">
                  <ReactQuill
                    theme="snow"
                    value={formData.description}
                    onChange={(val) => setFormData(prev => ({ ...prev, description: val }))}
                    className="h-64 mb-12"
                  />
                </div>
                {errors.description && <p className="text-sm text-red-500 mt-1">{errors.description}</p>}
              </div>

              <div className="grid md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    {language === 'id' ? 'Kategori' : 'Category'} <span className="text-red-500">*</span>
                  </label>
                  <select
                    name="category_id"
                    value={formData.category_id}
                    onChange={(e) => setFormData((prev: CreateCoursePayload) => ({ ...prev, category_id: Number(e.target.value) }))}
                    className={`w-full rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50 ${
                      errors.category_id ? 'border-red-500' : 'border-gray-300'
                    }`}
                    disabled={isSubmitting || isLoadingCategories}
                  >
                    <option value={0} disabled>
                      {isLoadingCategories ? 'Loading...' : (language === 'id' ? 'Pilih Kategori' : 'Select Category')}
                    </option>
                    {categories.map((category) => (
                      <option key={category.id} value={category.id}>
                        {category.name}
                      </option>
                    ))}
                  </select>
                  {errors.category_id && <p className="text-sm text-red-500 mt-1">{errors.category_id}</p>}
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    {language === 'id' ? 'Bahasa' : 'Language'}
                  </label>
                  <select
                    name="language"
                    value={formData.language}
                    onChange={handleInputChange}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
                    disabled={isSubmitting}
                  >
                    <option value="Indonesia">Indonesia</option>
                    <option value="English">English</option>
                  </select>
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    {language === 'id' ? 'Tipe Kursus' : 'Course Type'}
                  </label>
                  <select
                    name="type"
                    value={formData.type}
                    onChange={handleInputChange}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
                    disabled={isSubmitting}
                  >
                    <option value="self_paced">Self Paced</option>
                    <option value="structured">Structured</option>
                  </select>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    {language === 'id' ? 'Level' : 'Level'}
                  </label>
                  <select
                    name="level"
                    value={formData.level}
                    onChange={handleInputChange}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
                    disabled={isSubmitting}
                  >
                    <option value="beginner">Beginner</option>
                    <option value="intermediate">Intermediate</option>
                    <option value="advanced">Advanced</option>
                    <option value="all_levels">All Levels</option>
                  </select>
                </div>
              </div>
            </Card>
          )}

          {/* Step 2: Pricing & Media */}
          {currentStep === 2 && (
            <Card className="p-6 space-y-4">
              <h2 className="text-lg font-semibold text-gray-900 border-b pb-2 mb-4">
                {language === 'id' ? 'Harga & Media' : 'Pricing & Media'}
              </h2>

              <div className="grid md:grid-cols-2 gap-4">
                <Input
                  label={language === 'id' ? 'Harga (Rp)' : 'Price (IDR)'}
                  type="number"
                  name="price"
                  min="0"
                  value={formData.price}
                  onChange={handleNumberChange}
                  disabled={isSubmitting}
                  error={errors.price}
                  required
                />
                <Input
                  label={language === 'id' ? 'Harga Diskon (Opsional)' : 'Discount Price (Optional)'}
                  type="number"
                  name="discount_price"
                  min="0"
                  value={formData.discount_price}
                  onChange={handleNumberChange}
                  disabled={isSubmitting}
                />
              </div>

              <div className="space-y-2">
                <FileUpload
                  label={language === 'id' ? 'Thumbnail Kursus' : 'Course Thumbnail'}
                  onChange={handleFileChange}
                  value={formData.thumbnail}
                  accept="image/*"
                  helperText="Recommended size: 1280x720 pixels (16:9 aspect ratio)"
                />
              </div>
            </Card>
          )}

          {/* Step 3: Curriculum Info */}
          {currentStep === 3 && (
            <Card className="p-6 space-y-4">
              <h2 className="text-lg font-semibold text-gray-900 border-b pb-2 mb-4">
                {language === 'id' ? 'Informasi Kurikulum' : 'Curriculum Info'}
              </h2>

              <DynamicList
                label={language === 'id' ? 'Persyaratan' : 'Requirements'}
                items={formData.requirements}
                onChange={(items) => setFormData((prev: CreateCoursePayload) => ({ ...prev, requirements: items }))}
                placeholder={language === 'id' ? 'Tambahkan persyaratan...' : 'Add requirement...'}
                helperText={language === 'id' 
                  ? 'Daftar pengetahuan atau alat yang diperlukan sebelum mengikuti kursus.' 
                  : 'List of knowledge or tools required before taking the course.'}
              />

              <DynamicList
                label={language === 'id' ? 'Hasil Pembelajaran' : 'Learning Outcomes'}
                items={formData.outcomes}
                onChange={(items) => setFormData((prev: CreateCoursePayload) => ({ ...prev, outcomes: items }))}
                placeholder={language === 'id' ? 'Tambahkan hasil...' : 'Add outcome...'}
                helperText={language === 'id'
                  ? 'Apa yang akan siswa pelajari setelah menyelesaikan kursus ini?'
                  : 'What will students learn after completing this course?'}
              />

              <DynamicList
                label={language === 'id' ? 'Target Audiens' : 'Target Audience'}
                items={formData.target_audience}
                onChange={(items) => setFormData((prev: CreateCoursePayload) => ({ ...prev, target_audience: items }))}
                placeholder={language === 'id' ? 'Tambahkan audiens...' : 'Add audience...'}
                helperText={language === 'id'
                  ? 'Siapa yang sebaiknya mengikuti kursus ini?'
                  : 'Who should take this course?'}
              />
            </Card>
          )}

          {/* Action Buttons */}
          <div className="flex justify-between items-center pt-4">
            <Button
              type="button"
              variant="ghost"
              onClick={() => {
                if (currentStep === 1) navigate('/instructor/courses');
                else prevStep();
              }}
              disabled={isSubmitting}
              leftIcon={<ArrowLeft className="w-4 h-4" />}
            >
              {currentStep === 1 
                ? (language === 'id' ? 'Batal' : 'Cancel')
                : (language === 'id' ? 'Kembali' : 'Back')}
            </Button>

            <div className="flex gap-3">
              {currentStep < 3 ? (
                <Button
                  type="button"
                  onClick={nextStep}
                  className="bg-blue-600 hover:bg-blue-700 min-w-[120px]"
                >
                  {language === 'id' ? 'Lanjut' : 'Next'}
                </Button>
              ) : (
                <Button
                  type="submit"
                  disabled={isSubmitting}
                  className="bg-blue-600 hover:bg-blue-700 min-w-[150px]"
                >
                  {isSubmitting ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      {language === 'id' ? 'Menyimpan...' : 'Saving...'}
                    </>
                  ) : (
                    <>
                       <Save className="w-4 h-4 mr-2" />
                       {language === 'id' ? 'Simpan Kursus' : 'Save Course'}
                    </>
                  )}
                </Button>
              )}
            </div>
          </div>
        </form>
      </div>
    </DashboardLayout>
  );
}
