import { useState, type FormEvent, type ChangeEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Save, Loader2 } from 'lucide-react';
import { DashboardLayout } from '@/components/layouts';
import { Card, Button, Input, Textarea } from '@/components/ui';
import { FileUpload } from '@/components/ui/FileUpload';
import { DynamicList } from '@/components/ui/DynamicList';
import { useLanguage } from '@/context/LanguageContext';
import { 
  useCreateCourseMutation, 
  useGetCategoriesQuery,
  type CreateCoursePayload 
} from '@/store/features/instructor/instructorApiSlice';

export function InstructorCreateCoursePage() {
  const { language } = useLanguage();
  const navigate = useNavigate();
  const [createCourse, { isLoading: isSubmitting }] = useCreateCourseMutation();
  const { data: categories = [], isLoading: isLoadingCategories } = useGetCategoriesQuery();

  const [formData, setFormData] = useState<CreateCoursePayload>({
    title: '',
    slug: '',
    thumbnail: '',
    subtitle: '',
    description: '',
    category_id: 0,
    type: 'self_paced',
    level: 'beginner',
    language: 'Indonesia',
    price: 0,
    discount_price: 0,
    requirements: [],
    outcomes: [],
    target_audience: [],
  });

  const [slugAutogenerated, setSlugAutogenerated] = useState(true);
  const [thumbnailFile, setThumbnailFile] = useState<File | null>(null);

  const handleInputChange = (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    
    setFormData((prev: CreateCoursePayload) => {
      const newData = { ...prev, [name]: value };
      
      // Auto-generate slug from title if enabled
      if (name === 'title' && slugAutogenerated) {
        newData.slug = value
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/(^-|-$)+/g, '');
      }
      
      return newData;
    });
  };

  const handleNumberChange = (e: ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev: CreateCoursePayload) => ({ ...prev, [name]: Number(value) }));
  };

  const handleFileChange = (file: File | null) => {
    if (file) {
      setThumbnailFile(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        setFormData((prev: CreateCoursePayload) => ({ ...prev, thumbnail: reader.result as string }));
      };
      reader.readAsDataURL(file);
    } else {
      setThumbnailFile(null);
      setFormData((prev: CreateCoursePayload) => ({ ...prev, thumbnail: '' }));
    }
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    try {
      const formDataToSend = new FormData();
      formDataToSend.append('title', formData.title);
      formDataToSend.append('slug', formData.slug);
      formDataToSend.append('subtitle', formData.subtitle);
      formDataToSend.append('description', formData.description);
      formDataToSend.append('category_id', String(formData.category_id));
      formDataToSend.append('type', formData.type);
      formDataToSend.append('level', formData.level);
      formDataToSend.append('language', formData.language);
      formDataToSend.append('price', String(formData.price));
      
      if (formData.discount_price && formData.discount_price > 0) {
        formDataToSend.append('discount_price', String(formData.discount_price));
      }

      if (thumbnailFile) {
        formDataToSend.append('thumbnail', thumbnailFile);
      }

      formData.requirements.forEach((req, index) => formDataToSend.append(`requirements[${index}]`, req));
      formData.outcomes.forEach((out, index) => formDataToSend.append(`outcomes[${index}]`, out));
      formData.target_audience.forEach((aud, index) => formDataToSend.append(`target_audience[${index}]`, aud));

      await createCourse(formDataToSend).unwrap();
      navigate('/instructor/courses');
    } catch (error) {
      console.error('Failed to create course:', error);
      // Ideally show toast notification here
      alert('Failed to create course. Please try again.');
    }
  };

  return (
    <DashboardLayout>
      <div className="max-w-4xl mx-auto pb-10">
        <div className="flex items-center gap-4 mb-6">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate('/instructor/courses')}
            className="rounded-full aspect-square p-2"
          >
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">
              {language === 'id' ? 'Buat Kursus Baru' : 'Create New Course'}
            </h1>
            <p className="text-gray-600">
              {language === 'id' 
                ? 'Isi informasi kursus Anda di bawah ini.' 
                : 'Fill in your course information below.'}
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Basic Information */}
          <Card className="p-6 space-y-4">
            <h2 className="text-lg font-semibold text-gray-900 border-b pb-2 mb-4">
              {language === 'id' ? 'Informasi Dasar' : 'Basic Information'}
            </h2>
            
            <div className="grid md:grid-cols-2 gap-4">
              <Input
                label={language === 'id' ? 'Judul Kursus' : 'Course Title'}
                name="title"
                value={formData.title}
                onChange={handleInputChange}
                disabled={isSubmitting}
                required
              />
              <Input
                label="Slug"
                name="slug"
                value={formData.slug}
                onChange={(e) => {
                  setSlugAutogenerated(false);
                  handleInputChange(e);
                }}
                disabled={isSubmitting}
                required
              />
            </div>

            <Input
              label={language === 'id' ? 'Subjudul' : 'Subtitle'}
              name="subtitle"
              value={formData.subtitle}
              onChange={handleInputChange}
              disabled={isSubmitting}
              required
            />

            <Textarea
              label={language === 'id' ? 'Deskripsi' : 'Description'}
              name="description"
              value={formData.description}
              onChange={handleInputChange}
              rows={5}
              disabled={isSubmitting}
              required
            />

            <div className="grid md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {language === 'id' ? 'Kategori' : 'Category'}
                </label>
                <select
                  name="category_id"
                  value={formData.category_id}
                  onChange={(e) => setFormData((prev: CreateCoursePayload) => ({ ...prev, category_id: Number(e.target.value) }))}
                  className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
                  disabled={isSubmitting || isLoadingCategories}
                  required
                >
                  <option value={0} disabled>
                    {isLoadingCategories ? 'Loading...' : (language === 'id' ? 'Pilih Kategori' : 'Select Category')}
                  </option>
                  {categories.map((category) => (
                    <option key={category.id} value={category.id}>
                      {category.name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {language === 'id' ? 'Bahasa' : 'Language'}
                </label>
                <select
                  name="language"
                  value={formData.language}
                  onChange={handleInputChange}
                  className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
                  disabled={isSubmitting}
                >
                  <option value="Indonesia">Indonesia</option>
                  <option value="English">English</option>
                </select>
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {language === 'id' ? 'Tipe Kursus' : 'Course Type'}
                </label>
                <select
                  name="type"
                  value={formData.type}
                  onChange={handleInputChange}
                  className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
                  disabled={isSubmitting}
                >
                  <option value="self_paced">Self Paced</option>
                  <option value="structured">Structured</option>
                </select>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {language === 'id' ? 'Level' : 'Level'}
                </label>
                <select
                  name="level"
                  value={formData.level}
                  onChange={handleInputChange}
                  className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
                  disabled={isSubmitting}
                >
                  <option value="beginner">Beginner</option>
                  <option value="intermediate">Intermediate</option>
                  <option value="advanced">Advanced</option>
                  <option value="all_levels">All Levels</option>
                </select>
              </div>
            </div>
          </Card>

          {/* Pricing & Media */}
          <Card className="p-6 space-y-4">
            <h2 className="text-lg font-semibold text-gray-900 border-b pb-2 mb-4">
              {language === 'id' ? 'Harga & Media' : 'Pricing & Media'}
            </h2>

            <div className="grid md:grid-cols-2 gap-4">
              <Input
                label={language === 'id' ? 'Harga (Rp)' : 'Price (IDR)'}
                type="number"
                name="price"
                min="0"
                value={formData.price}
                onChange={handleNumberChange}
                disabled={isSubmitting}
                required
              />
              <Input
                label={language === 'id' ? 'Harga Diskon (Opsional)' : 'Discount Price (Optional)'}
                type="number"
                name="discount_price"
                min="0"
                value={formData.discount_price}
                onChange={handleNumberChange}
                disabled={isSubmitting}
              />
            </div>

            <div className="space-y-2">
              <FileUpload
                label={language === 'id' ? 'Thumbnail Kursus' : 'Course Thumbnail'}
                onChange={handleFileChange}
                value={formData.thumbnail}
                accept="image/*"
                helperText="Recommended size: 1280x720 pixels (16:9 aspect ratio)"
              />
            </div>
          </Card>

          {/* Curriculum Info */}
          <Card className="p-6 space-y-4">
            <h2 className="text-lg font-semibold text-gray-900 border-b pb-2 mb-4">
              {language === 'id' ? 'Informasi Kurikulum' : 'Curriculum Info'}
            </h2>

            <DynamicList
              label={language === 'id' ? 'Persyaratan' : 'Requirements'}
              items={formData.requirements}
              onChange={(items) => setFormData((prev: CreateCoursePayload) => ({ ...prev, requirements: items }))}
              placeholder={language === 'id' ? 'Tambahkan persyaratan...' : 'Add requirement...'}
              helperText={language === 'id' 
                ? 'Daftar pengetahuan atau alat yang diperlukan sebelum mengikuti kursus.' 
                : 'List of knowledge or tools required before taking the course.'}
            />

            <DynamicList
              label={language === 'id' ? 'Hasil Pembelajaran' : 'Learning Outcomes'}
              items={formData.outcomes}
              onChange={(items) => setFormData((prev: CreateCoursePayload) => ({ ...prev, outcomes: items }))}
              placeholder={language === 'id' ? 'Tambahkan hasil...' : 'Add outcome...'}
              helperText={language === 'id'
                ? 'Apa yang akan siswa pelajari setelah menyelesaikan kursus ini?'
                : 'What will students learn after completing this course?'}
            />

            <DynamicList
              label={language === 'id' ? 'Target Audiens' : 'Target Audience'}
              items={formData.target_audience}
              onChange={(items) => setFormData((prev: CreateCoursePayload) => ({ ...prev, target_audience: items }))}
              placeholder={language === 'id' ? 'Tambahkan audiens...' : 'Add audience...'}
              helperText={language === 'id'
                ? 'Siapa yang sebaiknya mengikuti kursus ini?'
                : 'Who should take this course?'}
            />
          </Card>

          {/* Submit Action */}
          <div className="flex justify-end gap-3 pt-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => navigate('/instructor/courses')}
              disabled={isSubmitting}
            >
              {language === 'id' ? 'Batal' : 'Cancel'}
            </Button>
            <Button
              type="submit"
              disabled={isSubmitting}
              className="bg-blue-600 hover:bg-blue-700 min-w-[150px]"
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  {language === 'id' ? 'Menyimpan...' : 'Saving...'}
                </>
              ) : (
                <>
                   <Save className="w-4 h-4 mr-2" />
                   {language === 'id' ? 'Simpan Kursus' : 'Save Course'}
                </>
              )}
            </Button>
          </div>
        </form>
      </div>
    </DashboardLayout>
  );
}
